apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  name: argocd-ui
  namespace: argocd
spec:
  tls:
  - hosts:
      - ###ARGOCDDNS###
    secretName: wild-tls
  rules:
  - host: ###ARGOCDDNS###
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: argocd-server
              port:
                number: 80
